### ISSUE TITLE
Select data from specific sensor?

### ISSUE THREAD

**Issue by matheusvvb-19** [kav-institute/imptc-dataset#1]
Hi, congratulations for the amazing work!!
I was wondering if would be possible to filter the dataset according to a specific sensor. For example: according to the paper, the tracks were collected using 6 cameras and 3 LiDAR sensors, right? Would it be possible to select only the data captured by one of those cameras and one of those LiDAR sensors?

I noticed that the `tracks.json` files indicate the source type of that data. For example, considering the `track.json` file of a VRU track, we have:

> source_type: Which sensor(s) are responsible for current object detection, 0 => Lidar, 1 => lidar+camera, 2 => camera

However, would it be possible to select, for example, a specific camera? Let's say, camera 1, camera 2, camera 3, etc.

Thank you in advance.

**Comment by mh-kav-institute** [comment]
Hi Matheus,
Based on the dataset's current uploaded status and data, this is not possible because the provided tracks are the result of our multi-sensor-fusion framework. However, the fusion framework is flexible regarding camera usage. The only restriction is to have at least two selected cameras with an overlapping FOV for 3D trajectory extraction.  The  LiDAR object detection runs on a combined point cloud derived from the three single sensor data.

Can you share more details of your target application? 

Regards

**Comment by matheusvvb-19** [comment]
Thank you for the quick response.

Yes, I can provide more details about my application. Here it is: my research group and I are developing a VRU-safety-based ecosystem for smart cities — i.e., a system that detects VRUs and warns nearby autonomous vehicles to prevent collisions. As we are at the beginning of the project, we want to start with a simple and limited scenario: an urban intersection equipped with just a few infrastructure sensors (one camera and one LiDAR). That's why I would like to filter the data to gather information captured by just one of the cameras.

I am interested in the IMPTC dataset because, besides the bounding boxes for VRUs and vehicles, it also provides VRU trajectories — which is a future focus of our research — as well as various contextual information (e.g., weather and segmentation map data).

**Comment by mh-kav-institute** [comment]
I will internally check if its possible to provide you some data with reduced camera usage. Whats possible is to have for example cam1+cam3+Lidars. Both cams monitor a single corner of the intersection. Could this help you?

**Comment by matheusvvb-19** [comment]
Thank you for your help.

If both cameras monitor a single corner of the intersection, then yes, this would help me a lot! How could I filter the data to select this reduced set? Would it be by using the `source_type` attribute - which I mentioned earlier? Or it must be another way?

**Comment by mh-kav-institute** [comment]
The official uploaded data does not allow for filtering for this. The 'source_type' attribute only describes which sensor modalities contribute to the current 3D object detection; it does not distinguish between specific camera or lidar sensors. 
We are internally checking the effort to extend the attribute and context in the way of your request, but this needs a little more time.

I can give you an update soon.

**Comment by matheusvvb-19** [comment]
Understood.
Thank you very much.

**Comment by mh-kav-institute** [comment]
Hi Matheus,
Reproducing the dataset and including the requested data is a fairly complex and time-consuming process. Therefore, we could not do this anymore. The dataset is a context-enriched dataset for trajectory prediction starting at the trajectory level. Your request is more related to the sensor data and object detection level.

**Comment by matheusvvb-19** [comment]
Hi, @mh-kav-institute.
I see.

But that's ok, no problems. Thank you for your help.
