### ISSUE TITLE
Individual scenes images (or video) available? (.mp4, .jpg)

### ISSUE THREAD

**Issue by matheusvvb-19** [kav-institute/imptc-dataset#2]
Hi.
Is it possible to access the individual `.mp4 ` file of a sequence? Or a set of `.jpg` images that forms a recorded sequence?

I'm asking this because I would like to train YOLO (a 2D object detection method) network on this dataset. Then, after training, I would like to plot the images with the bounding boxes of the objects predicted by YOLO.

Thank you in advance.

**Comment by kav-hareichert** [comment]
We can not provide raw image data due to European data protection guidelines.

**Comment by matheusvvb-19** [comment]
Oh, I see.
Thank you anyway.
